// <auto-generated />
using System;
using Bank.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bank.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224191735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bank.API.Models.BankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsMerchantAccount")
                        .HasColumnType("boolean");

                    b.Property<string>("MerchantId")
                        .HasColumnType("text");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId")
                        .IsUnique();

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("Bank.API.Models.CardToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardholderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvvHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpiryMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpiryYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaskedPan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CardHash")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("CardTokens");
                });

            modelBuilder.Entity("Bank.API.Models.PaymentTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AcquirerTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CardTokenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CustomerAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlobalTransactionId")
                        .HasColumnType("text");

                    b.Property<long>("MerchantAccountId")
                        .HasColumnType("bigint");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MerchantTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PspTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.HasIndex("MerchantAccountId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("Stan")
                        .IsUnique();

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Bank.API.Models.CardToken", b =>
                {
                    b.HasOne("Bank.API.Models.PaymentTransaction", "Transaction")
                        .WithOne("CardToken")
                        .HasForeignKey("Bank.API.Models.CardToken", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Bank.API.Models.PaymentTransaction", b =>
                {
                    b.HasOne("Bank.API.Models.BankAccount", "CustomerAccount")
                        .WithMany("CustomerTransactions")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bank.API.Models.BankAccount", "MerchantAccount")
                        .WithMany("MerchantTransactions")
                        .HasForeignKey("MerchantAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerAccount");

                    b.Navigation("MerchantAccount");
                });

            modelBuilder.Entity("Bank.API.Models.BankAccount", b =>
                {
                    b.Navigation("CustomerTransactions");

                    b.Navigation("MerchantTransactions");
                });

            modelBuilder.Entity("Bank.API.Models.PaymentTransaction", b =>
                {
                    b.Navigation("CardToken")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
